-- Create table
create table LIVUNIDA
(
  ncodiunida NUMBER not null,
  cdescunida VARCHAR2(255),
  csiglunida VARCHAR2(10)
);
-- Add comments to the table 
comment on table LIVUNIDA
  is 'Unidade de Medida';
-- Add comments to the columns 
comment on column LIVUNIDA.ncodiunida
  is 'código da unidade de medida';
comment on column LIVUNIDA.cdescunida
  is 'descrição da unidade de medida';
comment on column LIVUNIDA.csiglunida
  is 'sigla da unidade de medida';
-- Create/Recreate primary, unique and foreign key constraints 
alter table LIVUNIDA
  add constraint PK_LIVUNIDA primary key (NCODIUNIDA)
  using index;
  
  
insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (1, 'AMPOLA', 'AMPOLA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (2, 'BALDE', 'BALDE');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (3, 'BANDEJA', 'BANDEJ');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (4, 'BARRA', 'BARRA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (5, 'BISNAGA', 'BISNAG');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (6, 'BLOCO', 'BLOCO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (7, 'BOBINA', 'BOBINA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (8, 'BOMBONA', 'BOMB');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (9, 'CAPSULA', 'CAPS');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (10, 'CARTELA', 'CART');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (11, 'CENTO', 'CENTO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (12, 'CONJUNTO', 'CJ');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (13, 'CENTIMETRO', 'CM');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (14, 'CENTIMETRO QUADRADO', 'CM2');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (15, 'CAIXA', 'CX');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (16, 'CAIXA COM 2 UNIDADES', 'CX2');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (17, 'CAIXA COM 3 UNIDADES', 'CX3');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (18, 'CAIXA COM 5 UNIDADES', 'CX5');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (19, 'CAIXA COM 10 UNIDADES', 'CX10');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (20, 'CAIXA COM 15 UNIDADES', 'CX15');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (21, 'CAIXA COM 20 UNIDADES', 'CX20');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (22, 'CAIXA COM 25 UNIDADES', 'CX25');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (23, 'CAIXA COM 50 UNIDADES', 'CX50');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (24, 'CAIXA COM 100 UNIDADES', 'CX100');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (25, 'DISPLAY', 'DISP');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (26, 'DUZIA', 'DUZIA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (27, 'EMBALAGEM', 'EMBAL');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (28, 'FARDO', 'FARDO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (29, 'FOLHA', 'FOLHA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (30, 'FRASCO', 'FRASCO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (31, 'GALÃO', 'GALAO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (32, 'GARRAFA', 'GF');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (33, 'GRAMAS', 'GRAMAS');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (34, 'JOGO', 'JOGO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (35, 'QUILOGRAMA', 'KG');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (36, 'KIT', 'KIT');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (37, 'LATA', 'LATA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (38, 'LITRO', 'LITRO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (39, 'METRO', 'M');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (40, 'METRO QUADRADO', 'M2');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (41, 'METRO CÚBICO', 'M3');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (42, 'MILHEIRO', 'MILHEI');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (43, 'MILILITRO', 'ML');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (44, 'MEGAWATT HORA', 'MWH');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (45, 'PACOTE', 'PACOTE');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (46, 'PALETE', 'PALETE');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (47, 'PARES', 'PARES');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (48, 'PEÇA', 'PC');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (49, 'POTE', 'POTE');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (50, 'QUILATE', 'K');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (51, 'RESMA', 'RESMA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (52, 'ROLO', 'ROLO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (53, 'SACO', 'SACO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (54, 'SACOLA', 'SACOLA');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (55, 'TAMBOR', 'TAMBOR');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (56, 'TANQUE', 'TANQUE');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (57, 'TONELADA', 'TON');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (58, 'TUBO', 'TUBO');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (59, 'UNIDADE', 'UNID');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (60, 'VASILHAME', 'VASIL');

insert into LIVUNIDA (NCODIUNIDA, CDESCUNIDA, CSIGLUNIDA)
values (61, 'VIDRO', 'VIDRO');  