-- Create table
create table LIVAJICM
(
  ncodiajicm NUMBER not null,
  ccodiajicm VARCHAR2(10) not null,
  cdescajicm VARCHAR2(255) not null
);
-- Add comments to the table 
comment on table LIVAJICM
  is 'Ajuste de ICMS';
-- Add comments to the columns 
comment on column LIVAJICM.ncodiajicm
  is 'código do ajuste de icms';
comment on column LIVAJICM.ccodiajicm
  is 'código literal do ajuste de icms';
comment on column LIVAJICM.cdescajicm
  is 'descrição do ajuste de icms';
-- Create/Recreate primary, unique and foreign key constraints 
alter table LIVAJICM
  add constraint PK_LIVAJICM primary key (NCODIAJICM)
  using index;
alter table LIVAJICM
  add constraint UK_LIVAJICM unique (CCODIAJICM)
  using index;

  
 insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (1, 'PR820015', 'REDUÇÃO DE BC ITEM 15 ANEXO VI - INSUMOS AGROPECUÁRIOS');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (2, 'PR820016', 'REDUÇÃO DE BC ITEM 16 ANEXO VI - INSUMOS AGROPECUÁRIOS');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (3, 'PR830001', 'DIFERIMENTO PREV. INC.I ART. 28 ANEXO VIII ');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (4, 'PR830113', 'DIFERIMENTO PREV.INC.II ART. 44 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (5, 'PR840002', 'SUSPENSAO PREV. INC. II ART. 1 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (6, 'PR800013', 'NAO INCIDENCIA INC. XIV ART. 3');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (7, 'PR800014', 'NAO INCIDENCIA INC. XV ART. 3');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (8, 'PR800015', 'NAO INCIDENCIA INC.I § UNICO ART. 3');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (9, 'PR810015', 'ISENCAO PREV. ITEM 15 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (10, 'PR810041', 'ISENCAO PREV. ITEM 41 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (11, 'PR810047', 'ISENCAO PREV. ITEM 47 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (12, 'PR810112', 'ISENCAO PREV. ITEM 112 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (13, 'PR810118', 'ISENCAO PREV. ITEM 118 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (14, 'PR810123', 'ISENCAO PREV. ITEM 123 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (15, 'PR810124', 'ISENCAO PREV. ITEM 124 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (16, 'PR810171', 'ISENCAO PREV. ITEM 171 ANEXO V');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (17, 'PR830005', 'DIFERIMENTO PREV. ITEM 1 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (18, 'PR830007', 'DIFERIMENTO PREV. ITEM 3 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (19, 'PR830008', 'DIFERIMENTO PREV. SUB. 4.1 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (20, 'PR830014', 'DIFERIMENTO PREV. ITEM 9 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (21, 'PR830051', 'DIFERIMENTO PREV. ITEM 44 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (22, 'PR830060', 'DIFERIMENTO PREV. ITEM 53 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (23, 'PR830078', 'DIFERIMENTO PREV. ITEM 71 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (24, 'PR830084', 'DIFERIMENTO PREV. ITEM 77 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (25, 'PR830098', 'DIFERIMENTO PREV. ART. 32 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (26, 'PR830099', 'DIFERIMENTO PREV. ART. 39 ANEXO VII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (27, 'PR830101', 'DIFERIMENTO PREV. INC. I ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (28, 'PR830102', 'DIFERIMENTO PREV. INC. II ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (29, 'PR830105', 'DIFERIMENTO PREV. INC. V ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (30, 'PR830106', 'DIFERIMENTO PREV. INC. VI ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (31, 'PR830108', 'DIFERIMENTO INC. VII ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (32, 'PR830110', 'DIFERIMENTO INC. IX ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (33, 'PR830111', 'DIFERIMENTO PREV. INC. X ART. 42 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (34, 'PR830112', 'DIFERIMENTO PREV. INC. I ART. 44 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (35, 'PR830114', 'DIFERIMENTO PREV. INC. III ART. 44 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (36, 'PR830115', 'DIFERIMENTO PREV. INC. IV ART. 44 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (37, 'PR830118', 'DIFERIMENTO PREV. INC. VII ART. 44 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (38, 'PR840007', 'SUSPENSAO PREV. INC. VII ART. 1 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (39, 'PR840009', 'SUSPENSAO PREV. INC. IX ART. 1 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (40, 'PR830074', 'DIFERIMENTO PREV. ITEM 67 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (41, 'PR830052', 'DIFERIMENTO PREV. ITEM 45 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (42, 'PR800002', 'NAO INCIDENCIA INC. II ART. 3');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (43, 'PR830079', 'DIFERIMENTO PREV. ITEM 72 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (44, 'PR840001', 'SUSPENSAO PREV. INC. I ART. 1 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (45, 'PR830076', 'DIFERIMENTO PREV. ITEM 69 ART. 31 ANEXO VIII');

insert into LIVAJICM (NCODIAJICM, CCODIAJICM, CDESCAJICM)
values (46, 'PR810021', 'ISENCAO PREV. ITEM 21 ANEXO V');
 