-- Create table
create table LIVCOMEN
(
  ncodicomen NUMBER not null,
  cdes1comen VARCHAR2(255),
  cdes2comen VARCHAR2(255),
  cdifecomen VARCHAR2(10) default 'NÃO' not null,
  csuspcomen VARCHAR2(10) default 'NÃO' not null,
  cisencomen VARCHAR2(10) default 'NÃO' not null,
  cbcrzcomen VARCHAR2(10) default 'NÃO' not null,
  ccipicomen VARCHAR2(10) default 'NÃO' not null,
  cfisccomen VARCHAR2(10) default 'SIM' not null,
  cstatcomen VARCHAR2(10) not null
);
-- Add comments to the table 
comment on table LIVCOMEN
  is 'Comentário Fiscal';
-- Add comments to the columns 
comment on column LIVCOMEN.ncodicomen
  is 'código do comentário fiscal';
comment on column LIVCOMEN.cdes1comen
  is 'primeira descrição do comentário fiscal';
comment on column LIVCOMEN.cdes2comen
  is 'segunda descrição do comentário fiscal';
comment on column LIVCOMEN.cdifecomen
  is 'diferimento do comentário fiscal';
comment on column LIVCOMEN.csuspcomen
  is 'suspenso do comentário fiscal';
comment on column LIVCOMEN.cisencomen
  is 'isento do comentário fiscal';
comment on column LIVCOMEN.cbcrzcomen
  is 'base de calculo reduzido do comentário fiscal';
comment on column LIVCOMEN.ccipicomen
  is 'ipi do comentario fiscal';
comment on column LIVCOMEN.cfisccomen
  is 'comentario fiscal(SIM/NÃO)';
comment on column LIVCOMEN.cstatcomen
  is 'status do comentário fiscal(ATIVO/INATIVO)';
-- Create/Recreate primary, unique and foreign key constraints 
alter table LIVCOMEN
  add constraint PK_LIVCOMEN primary key (NCODICOMEN)
  using index;
  
insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (1, 'BC ICMS RED.CONF.CONV.ICMS Nº 52 DE 26/09/91', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (2, 'SUSP.PIS/COFINS CF ART 9ºLEI 10925/2004 C/ALT.11051/04', 'BC RED CF. DEC. 5141/01 ART.14 ANEXO II TAB.I ITEM 12 ', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (3, 'EMBAL.VAZIAS-LOCAL ENTREGA PR 317 GLEBA RIBEIRAO MARIN', 'GA, SAIDA P/ASTORGA JUNTO A UNIDADE DE REC. LIXO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (4, 'N/ DESNATURADO C/VOL.TEOR ALCOÓLICO>=97%(ANIDRO)', 'RE: 06/0294787-001 NCM:22.07.1000-99 TAXA:2,1611', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (5, 'REGIME ESPECIAL DE RECOLHIMENTO DO IMPOSTO Nº 0105', 'BC RED.P/70%CF.DEC5141/01 ART.14 ANEXO II TAB.I ITEM12', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (6, 'ICMS SUSPENSO CF RICMS 1980/07 ART 93 INC.IX E ART 279', 'IPI SUSPENSO CF ART.43 INC.III DEC. 7212/2010 RPI', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (7, 'NAO INCID. DE ICMS CF DEC 1980/07 ART.3 INC.XIII', 'IPI IMUNE CONF. DEC. 4544/02 ART. 18', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (8, 'ESTA CARGA CONTEM SOJA ROUNDUP READY E ESTA SUJEITO AO', 'VALOR DPI', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (9, 'NF DE ACORCO C/PAR.4 ART.266, ITEM A DO RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (10, 'PIS/COFINS SUSP.CF ART 9ºLEI 10925/04 ALT.LEI 11051/04', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (11, 'PROCEDIMENTO AUTORIZADO PELO REGIME ESPECIAL 3542/05', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (12, 'CLASSIF. NO IPI 23.03.20.00 NT', 'CONF.DEC 6066 DE 28/12/06', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (13, 'CLASSIF. NO IPI 22.07.10.90 NT', 'CONF. DEC. 6066 DE 28/12/06', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (14, 'ICMS REC SUBST.TRIBUTARIA CONF.DEC.2373/2008', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (15, 'CLASSIFICACAO FISCAL 38249089', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (16, 'IPI SUSPENSO CF ART.43 INC.III DEC. 7212/2010 RIPI', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (17, 'ISENTO CONF RICMS 1980/07 ANEXO I ITEM 73', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (18, 'ICMS SUSPENSO CONF RICMS 1980/07 ART 93 INC VII', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (19, 'ICMS DIF EM 33,33% CONF RICMS 1980/07 ART 95 ITEM 4', 'PROCEDIMENTO AUTORIZADO PELO REGIME ESPECIAL Nº3542/05', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (20, 'NAO INC. ICMS CF RICMS 1980/07 ART. 3 INC. II', 'IPI IMUNE CF ART. 18 INC. II DEC. 4544/02', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (21, 'ISENTO DE ICMS CONF.RICMS 1980/2007 AENXO I ITEM 101', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (22, 'ICMS REC SUBST TRIBUTARIA CF DC 2473/2559 E 2906/08', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (23, 'ICMS DIFERIDO CONF RICMS 1980/07 ART 99 ITEM X', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (24, 'ICMS SUSPENSO CONF. ICMS 1980/07 ART. 93 INC.I', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (25, 'CRED ICMS PRESUMIDO CF RICMS 1980/07 ANEXO III ITEM 25', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (26, 'ICMS SUSPENSO CONF. ART. 495 DO RICMS 1980/2007', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (27, 'NAO INCIDENCIA ICMS CF RICMS 1980/07 ART. 3 INC. II', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (28, 'NAO INCID. DO ICMS CF ART.3 INC II RICMS 1980/07', 'IPI IMUNE CF ART 18 INC II DEC. 7212/10', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (29, 'SUBS. TRIB. CONF. PROTOCOLO 41/2008', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (30, 'BC ICMS RED P/40%-ANEXO II ITEM 8-RICMS/PR 6080/2012 ', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (31, 'BC ICMS RED P/70%-ANEXO II ITEM 10 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (32, 'ICMS DIFERIDO CF ART 113 - RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (33, 'ICMS DIFERIDO CF ART 528 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (34, 'ICMS DIFERIDO CF ART 107 ITEM 3 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (35, 'ICMS DIFERIDO CF ART 107 ITEM 44 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (36, 'ICMS DIFERIDO CF ART 107 ITEM 9 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (37, 'NAO TRIBUTADA CF ART 3 INC II,§ UNICO RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (38, 'ICMS SUSPENSO CF ART. 105 INC. IX RICMS/PR 6080/12', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (39, 'BC ICMS RED P/40%-ANEXO II ITEM 9-RICMS/PR 6080/2012 ', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (40, 'ICMS DIFERIDO CF ART 107 ITEM 6 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (41, 'ICMS DIF EM 33,33% CF ART 108 INC. I RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (42, 'ICMS ISENTO CF ANEXO I-ITEM 21-F -RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (43, 'SUBST.TRIB.CF. ANEXO X ART. 29 IN VI -RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (44, 'SUBST. TRIB. CF. ANEXO X ART. 100 RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (45, 'SUBST.TRIBUTARIA CF ANEXO X-ART.112-RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (46, 'SUBST.TRIBUT.CF.ANEXO X-ART.104-RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (47, 'SUBS.TRIB. CF. ANEXO X - ART. 119-RICMS/PR DEC.6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (48, 'SUBS.TRIB.CF.ANEXO X-ART.114-RICMS-DEC.6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (49, 'SUBST.TRIB.CF.ANEXO X- ART.133-RICMS/PR-DEC.6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (50, 'SUB TRIB CF.ANEXO X ART 144 RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (51, 'PIS/COFINS MONOF-REV.ALIQ.0 CF.LEI 10485/02 §2ºART 3º', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (52, 'PIS/COFINS RED.ALIQ ZERO CF ART 1ºLEI 10925/04', 'E ART. 1 DA MP 609/13', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (53, 'ESTA CARGA CONTÉM SOJA INTACTA RR2 PRO E ESTÁ SUJEITA', 'AO VALOR DPI', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (54, 'SUBST.TRIB.CF.ART.135-A-ANEXO X-DEC.6080/2012 RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (55, 'ICMS SUSPENSO CF ART 334 DEC 6080/2012 RICMS/PR', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (56, 'ICMS SUB. TRIB. CF ANEXO X ART 88 DECRETO 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (57, 'BC ICMS RED EM 60%-ANEXO II ITEM 8-RICMS/PR 6080/2012 ', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (58, 'ICMS SUBST. TRIB. CONF. RICMS - ART. 489 ', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (59, 'SUBS.TRIBUT.CONF.ANEXO X - ART.97-RICMS/PR 6080/2012 ', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (60, 'ICMS SUSPENSO CF ART. 105 INC.II DO RICMS/PR 6080/12', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (61, 'SUBST. TRIB. CF. ANEXO X - ART. 19 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (62, 'BC REDUZIDA CF ANEXO II ITEM 15 B- RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (63, 'SUBST. TRIBUT. CF. ANEXO X-ART.93 - RICMS/PR 6018/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (64, 'ICMS DIFERIDO CF ART 107 ITEM 68 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (65, 'ICMS DIFERIDO CF ART 111 - RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (66, 'ICMS DIFERIDO CF ART 107 ITEM 71 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (67, 'ICMS DIFERIDO CF ART 546 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (68, 'SUBST TRIB CF ANEXO X ART 29 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (69, 'SUBST TRIBUT CONF ANEXO X  ART 67 RICMS/PR 6080/2012 ', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (70, 'SUBST TRIB CF ANEXO X ART 22 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (71, 'SUBST. TRIB. CF. ANEXO X-ART 89 RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (72, 'SUBS.TRIB.CONF. ANEXO X - ART 71 - RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (73, 'NAO INCIDENCIA CF ART.3 INC.XII-RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (74, 'SUBST.TRIB. CF. ANEXO X-ART.95-RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (75, 'ICMS DIFERIDO CONF ART 107 ITEM 42 RICMS 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (76, 'ICMS SUSPENSO CF ART. 105 INC.I DO RICMS/PR 6080/12', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (77, 'SUB. TRIB. CONF. ART 122 ANEXO X RICMS 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (78, 'ICMS DIFERIDO CF ART. 107 DEC. 6080/2012 RICMS/PR', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (79, 'SUB.TRIB.ANEXO X ART. 138 DEC.6080/2012 RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (80, 'SUBST.TRIB. CF. ART.15 ANEXO X -RICMS/PR DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (81, 'SUSP.PIS/COFINS CF.ART.54 LEI 12350/2010', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (82, 'BC RED. CF. ANEXO II ITEM 16-A-DEC.6080/12 - RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (83, 'ICMS ISENTO CF. ANEXO I ITEM 21-DEC.6080/2012-RICMS/PR', null, 'SIM', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (84, 'SUBST.TRIB.CF.ART.21-ANEXO X-RICMS/PR - DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (85, 'SUBST.TRIB.CF.ART.23-ANEXO X-RICMS/PR-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (86, 'SUBST.TRIB.ART.27-ANEXO X-RICMS/PR-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (87, 'SUBST.TRIB.ART.34-ANEXO X-RICMS/PR-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (88, 'SUBST.TRIB.CF.ART.36-ANEXO X-RICMS/PR - DEC.6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (89, 'SUBST.TRIB.CF.ART.95-ANEXO X-RICMS/PR - DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (90, 'SUBS.TRIB.CF.ART.110-ANEXO X-DEC.6.080/2012 - RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (91, 'SUB.TRIB.CF.ART.122-ANEXO X-DEC. 6080/2012 - RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (92, 'SUBST. TRIB. ART. 98 - ANEXO X RICMS/PR DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (93, 'PIS/COFINS RED.ALI.ZERO CONF.INC.XI LEI 10925/04', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (94, 'EMBAL. VAZIAS LOCAL ENTREGA  EST. OSVALDO DE MORAES ', 'CORREIA, 532, LOTE 16/2-A/62, PARQUE INDL- MARINGA-PR', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (95, 'ICMS SUBST.TRIB.CONF.RICMS 1980/2007-ART.536-I', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (96, 'ICMS DIFERIDO CF ART 107 ITEM 52 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (97, 'ICMS DIFERIDO CF ART 107 ITEM 66 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (98, 'ICMS DIFERIDO CF ART 107 ITEM 70 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (99, 'ICMS DIFERIDO CF ART 107 ITEM 76 RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (100, 'ICMS DIFERIDO CF ANEXO X ART 47  RICMS/PR 6080/12', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (101, 'ICMS SUSPENSO CF ANEXO X ART 47 RICMS/PR 6080/12', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (102, 'SUBST. TRIB. CF. ANEXO X-ART. 69  RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (103, 'BC REDUZIDA CF ANEXO II ITEM 16 B- RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (104, 'BC REDUZIDA CF ANEXO II ITEM 16 C- RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (105, 'BC REDUZIDA CF ANEXO II ITEM 15 A- RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (106, 'N TRIBUT CF ART 508 E ART 3 INC.II DO RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (107, 'SUBST TRIB CF ANEXO X ART 13 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (108, 'SUBST TRIB CF ANEXO X ART 71 INC III RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (109, 'ICMS ISENTO CF ANEXO I, ITEM 124 RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (110, 'BC DIF EM 33,33% CF ART 107 ITEM 4.1 RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (111, 'SUBST. TRIB. CF ANEXO X ART. 117 RICMS/PR 6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (112, 'SUSP.PIS/COFINS CF. ART. 29º -  LEI 12865/2013', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (113, 'SEM DESTAQUE ICMS CF ART.328 §4º. RICMS/PR DEC 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (114, 'SUBS TRIB CF ANEXO X ART 107 - DEC 6080/2012 RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (115, 'ICMS SUB.TRIB. CF ANEXO X ART15 RICMS/PR DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (116, 'BC REDUZIDA CF ANEXO II ITEM 11 - RICMS/PR 6080/12', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (117, 'SUBST.TRIB.CF.ART.36-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (118, 'SUBST.TRIB.CF.ART.25-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (119, 'SUBST.TRIB.CF.ART.129-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (120, 'SUBST.TRIB.CF.ART.100-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (121, 'SUBST.TRIB.CF.ART.124-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (122, 'SUB.TRIB.CF.ART.100-ANEXO X-DEC.6080/2012-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (123, 'ICMS DIFERIDO CONF. RICMS/PR 7871/2017 ANEXO 8 ITEM 44', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (124, 'BC ICMS RED. P/70% CF RICMS 7871/2017 ANEXO VI ITEM 16', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (125, 'ICMS SUSPENSO CF ANEXO VIII-ART.1 INC II-DEC 7871/2017', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (126, 'SUBS.TRIB.CF.ART.35-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (127, 'SUBS.TRIB.CF.ART.26-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (128, 'SUBS.TRIB.CF.ART.37-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (129, 'SUBS.TRIB.CF.ART.118-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (130, 'SUBS.TRIB.CF.ART.101-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (131, 'SUBS.TRIB.CF.ART.125-ANEXO IX-DEC.7871/2017', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (132, 'SUBS.TRIB.CF.ART.24-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (133, 'SUBS.TRIB.CF.ART.28-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (134, 'SUBS.TRIB.CF.ART.130-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (135, 'SUBS.TRIB.CF.ART.41-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (136, 'BC RED.CF.ANEXO VI-ITEM 21-II-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (137, 'SUBS.TRIB.CF.ART.99-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (138, 'ICMS SUSPENSO CF.ART.1 INC.IX-ANEXO VIII-DEC.7871/2017', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (139, 'ICMS SUSPENSO CF.ART.1-INC.I-ANEXO VIII-DEC.7871/2017', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (140, 'ICMS DIFERIDO CF.ART.31-ITEM 9-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (141, 'ICMS DIFERIDO CF.ART.31-ITEM 53-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (142, 'ICMS DIFERIDO CF.ART.31-ITEM 72-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (143, 'SUBST.TRIB.CF.ART.116-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (144, 'ICMS DIF. CF.ART.60-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (145, 'ICMS SUSP. CF.ART.60-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (146, 'NAO TRIB.CF ART.3 INC II,§ UNICO DEC.7871/17-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (147, 'BC DIF.EM 33,33%CF.ART.31-ITEM 4.1-ANX.VIII-DC.7871/17', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (148, 'ICMS NAO TRIBUTADO CF ART 578 DO RICMS/PR 7871/2017', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (149, 'ICMS.DIF EM 33,33%CF.ART 28-INC.I-ANX.VIII-DC 7871/17', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (150, 'ICMS DIF.CF.ART.31-ITEM 67-ANEXO VIII RICMS/PR 7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (151, 'ICMS DIFERIDO CF. ART.39-ANEXO VIII-RICMS/PR 7871/2017', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (152, 'SUBS.TRIB.CF.ART.123-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (153, 'BC RED. CF ANEXO VI-ITEM 22-II-DEC.7871/2017 RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (154, 'ICMS SUSPENSO CONF. RICMS 7871/17 ANEXO VIII ART.2º', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (155, 'ICMS DIFERIDO CF.ART.31-ITEM 69-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (156, 'ICMS ST RICMS 7871/17 ANEXO IX,CP I SEC XIII ART 99 ', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (157, 'ICMS ST RICMS 7871/17 ANEXO IX,CP I SEC XVI ART 105', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (158, 'SUBS.TRIB.CF.ART. 96 -ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (159, 'ICMS NAO TRIBUTADO CONF. RICMS/PR 7871/17 ART. 578', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (160, 'ICMS DIF CF ART 32 ANEXO VIII-DEC 7871/2017-RICMS/PR', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (161, 'ICMS NAO TRIB.CF. ART.578 §4º-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (162, 'ICMS DIF ART.31 ITEM 67-ANX.VIII-RICMS/PR DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (163, 'ICMS DIF ART.31 ITEM 45 ANX VIII RICMS/PR DEC 7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (164, 'ICMS DIF ART.31 ITEM 71 ANXO VIII RICMS/PR DEC 7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (165, 'ICMS DIF CF ART. 31 ITEM 3 ANEXO VIII DEC 7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (166, 'ICMS SUSPENSO CF ART.1 INC.I ANEXO VIII DEC 7871/17', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (167, 'ICMS ST CF ART 121-ANEXO IX-DEC.7871/17 RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (168, 'SUBST.TRIB.CF.ART.117-ANEXO X-DEC.6080/2012', null, 'SIM', 'NÃO', 'SIM', 'SIM', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (169, 'SUBS.TRIB.CF.ART.23-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (170, 'SUBST.TRIB.CF.ART.34-ANEXO X-DEC.6.080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (171, 'SUBST.TRIB.CF.ART.40-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (172, 'SUBST.TRIB.CF.ART.27-ANEXO X-DEC.6080/2012', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (173, 'ICMS DIF.CF.ART.44-ANEXO VIII-RICMS/PR DEC.7871/2017', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (174, 'ICMS ST CF ART.24-ANEXO IX-RICMS/PR DEC 7871/2017', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (175, 'ICMS ST CF. ART.35-ANEXO IX-RICMS/PR DEC 7871/2017', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (176, 'BC RED EM 60% CF ANEXO VI-ITEM 15-RICMS/PR-DEC 7871/17', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (177, 'BC RED P/70% CF ANEXO VI-ITEM 16-RICMS/PR-DEC 7871/17', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (178, 'SUBS.TRIB.CF.ART.109-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (179, 'SUBS.TRIB.CF.ART.105-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (180, 'ICMS DIFERIDO CF.ANEXO VIII-ART. 32-DEC.7871/2017', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (181, 'ICMS DIF EM 33,33% CF ART 28-ANX VIII RICMS/PR 7871/17', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (182, 'ICMS DIFERIDO CF.ART.31-ITEM 77-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (183, 'ICMS SUSPENSO CF RICMS 7871/17 ANEXO VIII ART 1 INC IX', null, 'NÃO', 'SIM', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (184, 'ICMS ST RICMS PR 7871/17 ANEXO IX CP I SEC V ART 28', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (185, 'SUBS.TRIB.CF.ART.107-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (186, 'ICMS DIF.CF.ART.31 ITEM 69-ANEXO VIII-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (187, 'ICMS DIF ART 42 - ANEXO VIII- RICMS/PR-DEC.7871/17', null, 'SIM', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (188, 'ICMS ST CF ART 128-ANEXO IX-DEC.7871/17-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (189, 'ICMS ISENTO CF ANEXO V ITEM 123 - DEC.7871/17 ', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (190, 'BC RED.CF.ANEXO VI-ITEM 18-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'SIM', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (191, 'SUBST.TRIB.CF.ART.118-ANEXO IX-DEC.7871/2017-RICMS/PR', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (192, 'NAO INCID. ICMS CF ART.237 §11 RICMS/PR DEC.7871/17 ', null, 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'SIM', 'ATIVO');

insert into LIVCOMEN (NCODICOMEN, CDES1COMEN, CDES2COMEN, CDIFECOMEN, CSUSPCOMEN, CISENCOMEN, CBCRZCOMEN, CCIPICOMEN, CFISCCOMEN, CSTATCOMEN)
values (193, 'ICMS ISENTO CF. ANEXO V ITEM 21-DEC.7871/17-RICMS/PR', null, 'NÃO', 'NÃO', 'SIM', 'NÃO', 'NÃO', 'SIM', 'ATIVO');
  
